lam = _{ "λ" | "\\" }
_pi = _{ "π" | "\\pi" }

ident = @{ ALPHABETIC ~ ASCII_ALPHANUMERIC* }
ident_nullable = @{ ALPHABETIC ~ ASCII_ALPHANUMERIC* | "_" }

var = @{ ident }
app = { "(" ~ expr ~ ")" }
abs = { lam ~ ident_nullable ~ ":" ~ ty ~ "." ~ expr }
pi = { _pi ~ ident_nullable ~ ":" ~ ty ~ "." ~ ty }
kind = { "*" | "□" | "[]" }
term = { abs | app | pi | kind | var}
expr = { term ~ (" " ~ term)* }
ty = { "("? ~ expr ~")"? }

lambda = { SOI ~ expr ~ EOI }
